### ISSUE TITLE
Created is undefined here

### ISSUE THREAD

**Issue by floek** [grenagit/MMM-ToDo#1]
Hi,

thanks for your work. I've the problem, my CalDAV Server does not fill the "created" attribute, so MMM-ToDo is failing with "Do not receive usable data."

Here DTSTAMP is used.

Maybe we can relax this a little bit.

Best,
floek

**Comment by grenagit** [comment]
Just out of curiosity, what is your CalDAV server that uses the `DTSTAMP` field instead of `CREATED`?

**Comment by floek** [comment]
Hi, I'm using good old zimbra. Thank for merging.
